// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MudeiONomeMeuDeus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudeiONomeMeuDeus));
        
        string IMigrationMetadata.Id
        {
            get { return "201209090008597_MudeiONomeMeuDeus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
